/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package mainModule

import consumer.ConsumerKafka
import org.apache.kafka.clients.consumer.KafkaConsumer
import org.apache.kafka.common.serialization.StringDeserializer

import java.util.Properties
import scala.jdk.CollectionConverters.{asJavaCollection, iterableAsScalaIterableConverter}
import dataFrame.DataFrame

object App {
  def main(args: Array[String]): Unit = {
    val dataFrame=new DataFrame()
    val consumerKafka = new ConsumerKafka()
    consumerKafka.produceResult()
    println(dataFrame.array)
    
  }
}

