/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.example.mongo

import com.mongodb.client.MongoClient
import com.mongodb.client.MongoClients
import com.example.data.Data
import org.bson.Document
import org.bson.types.ObjectId
import com.example.kafkaConsumer.Consumer



object App {
  def main(args: Array[String]): Unit = {
    val mongoConnect:MongoClient =MongoClients.create( "paste your url here")
    try{
        val database = mongoConnect.getDatabase("Test")        
        new Consumer().produceResult(database,"Iris")
    }catch{
      case e: Exception => println("exception "+e)
    }
    
    
  }
}
